[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Florian Vall√©e <florian@vallee.xyz>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
counter = "0.5.2"
regex = "1"
